pipeline {
  agent any
  stages {
    stage('Trigger remote build') {
      steps {
        powershell(returnStatus: true, script: 'D:\\Tools\\host-script.ps1 "firefox\beta\turbo.me")
      }
    }
  }
}